apiVersion: vpn.wireguard-operator.io/v1alpha1
kind: WireguardPeer
metadata:
  name: wireguardpeer-sample
spec:
  wireguardRef: "wireguard-sample"
  # Networks that this peer is responsible for routing (e.g., the peer's local LAN)
  # Other peers can reach these networks through the WireGuard server.
  # routes:
  #   - "10.10.30.0/24"
